In [ ]:
from datasets import load_dataset

ds = load_dataset("axmeu/BPE_WP_dataset")
train_texts = ds["train"]["text"][:500]
test_texts  = ds["test"]["text"][:50]

/home/onyxia/work/.pixi/envs/default/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
import sys
sys.path.append("..")
from src.tokenizers.BPE.naive import BPE
from src.tokenizers.BPE.Fast_BPE import FastBPE

In [ ]:
bpe = BPE(vocab_size=20_000)
bpe.train(train_texts)

for text in test_texts:
    print(f"BPE: {bpe.encode(text)[:10]}")
    print()

Initial vocab size: 63
Unique words: 99,549
1000 merges... vocab size: 1063
2000 merges... vocab size: 2063
3000 merges... vocab size: 3063
4000 merges... vocab size: 4063
5000 merges... vocab size: 5063

In [4]:
fast_bpe = FastBPE(vocab_size=8_000)
fast_bpe.train(train_texts)

for text in test_texts:
    print(f"Fast BPE      : {fast_bpe.encode(text)[:10]}")

Initial vocab size: 37
Unique words: 85,923
1000 merges... vocab size: 1037
2000 merges... vocab size: 2037
3000 merges... vocab size: 3037
4000 merges... vocab size: 4037
5000 merges... vocab size: 5037
6000 merges... vocab size: 6037
7000 merges... vocab size: 7037
Training complete in 3.76s
Final vocab size: 8000
Fast BPE      : ['m', 'u', 'c', 'o', 'nate</w>', 'l', 'a', 'c', 't', 'o']
Fast BPE      : ['the</w>', 'a', 'nteri', 'or</w>', 'tr', 'i', 'angle</w>', 'i', 's</w>', 'a</w>']
Fast BPE      : ['the</w>', 'd', 'ean</w>', 'heritage</w>', 'c', 'e', 'n', 'tr', 'e</w>', 'i']
Fast BPE      : ['dur', 'b', 'a', 'n', 'ville</w>', 'i', 's</w>', 'a</w>', 'town</w>', 'i']
Fast BPE      : ['this</w>', 'i', 's</w>', 'a</w>', 'l', 'i', 'st</w>', 'of</w>', 'rivers</w>', 'of</w>']
Fast BPE      : ['b', 'all', 'y', 'm', 'ar', 'ti', 'n</w>', 'i', 's</w>', 'o']
Fast BPE      : ['r', 'ay</w>', 'i', 's</w>', 'a</w>', 's', 'o', 'ng</w>', 'b', 'y</w>']
Fast BPE      : ['christopher</w>', 'lee</w>', 'c', 'a', 'nty</w>', 'b', 'or', 'n</w>', 'november</w>', '10</w>']
Fast BPE      : ['the</w>', 'deep</w>', 'c', 'ervi', 'cal</w>', 'f', 'asci', 'a</w>', 'or</w>', 'f']
Fast BPE      : ['the</w>', 'c', 'ervi', 'cal</w>', 'f', 'asci', 'a</w>', 'i', 's</w>', 'f']
Fast BPE      : ['m', 'i', 'l', 'n', 'er', 'ton</w>', 'i', 's</w>', 'a</w>', 's']
Fast BPE      : ['pro', 'b', 'l', 'em', 's</w>', 'of</w>', 'p', 'o', 'st</w>', 'communi']
Fast BPE      : ['h', 'e', 'n', 'r', 'y</w>', 'regi', 'nald</w>', 'h', 'ol', 'l']
Fast BPE      : ['bay</w>', 'farm</w>', 'island</w>', 'i', 's</w>', 'a</w>', 'district</w>', 'of</w>', 'the</w>', 'city</w>']
Fast BPE      : ['s', 'or', 'did</w>', 'h', 'u', 'm', 'or</w>', 'was</w>', 'an</w>', 'american</w>']
Fast BPE      : ['fi', 'g', 'u', 'r', 'e</w>', '8', '</w>', 'r', 'a', 'ci']
Fast BPE      : ['a', 'v', 'r', 'a', 'h', 'am</w>', 'fri', 'edm', 'an</w>', 'i']
Fast BPE      : ['the</w>', 'investig', 'a', 't', 'or', 's</w>', 'i', 's</w>', 'a</w>', 'b']
Fast BPE      : ['c', 'err', 'o</w>', 'b', 'o', 'n', 'e', 'te</w>', 'i', 's</w>']
Fast BPE      : ['g', 'l', 'a', 's', 'g', 'ow</w>', 'w', 'al', 'ker</w>', 'i']
Fast BPE      : ['m', 'a', 'n', 'd', 'el', 'ate</w>', 'r', 'a', 'cem', 'ase</w>']
Fast BPE      : ['the</w>', 'h', 'i', 'g', 'h', '</w>', 'p', 'er', 'form', 'a']
Fast BPE      : ['che', 's', 's', 'game</w>', 'i', 's</w>', 'a</w>', 'b', 'r', 'i']
Fast BPE      : ['derm', 'a', 'c', 'e', 'ntor</w>', 'vari', 'abili', 's</w>', 'also</w>', 'known</w>']
Fast BPE      : ['kar', 'o</w>', 'may</w>', 'r', 'e', 'f', 'er</w>', 'to</w>', 'ethnic</w>', 'groups</w>']
Fast BPE      : ['christopher</w>', 'sha', 'wn</w>', 'p', 'a', 'tr', 'i', 'ck</w>', 'c', 'a']
Fast BPE      : ['k', 'y', 'k', 'k', 'os</w>', 'monastery</w>', 'or</w>', 'for</w>', 'sh', 'or']
Fast BPE      : ['this</w>', 'i', 's</w>', 'a</w>', 'l', 'i', 'st</w>', 'of</w>', 'media</w>', 'related</w>']
Fast BPE      : ['the</w>', 'armenian</w>', 'national</w>', 'phil', 'h', 'ar', 'm', 'o', 'ni', 'c</w>']
Fast BPE      : ['table</w>', 'vi', 'ew</w>', 'i', 's</w>', 'a</w>', 'west</w>', 'c', 'o', 'a']
Fast BPE      : ['the</w>', 'a', 'x', 'i', 'l', 'l', 'ar', 'y</w>', 'sh', 'eath</w>']
Fast BPE      : ['the</w>', 'tr', 'o', 'tu', '</w>', 'i', 's</w>', 'a</w>', 'r', 'i']
Fast BPE      : ['people</w>', 's</w>', 'revolutionary</w>', 'party</w>', 'i', 's</w>', 'a</w>', 'name</w>', 'u', 'sed</w>']
Fast BPE      : ['r', 'o', 'b', 'ert</w>', 'l', 'l', 'oyd</w>', 'may</w>', 'r', 'e']
Fast BPE      : ['g', 'e', 'n', 'tlem', 'en</w>', 'and</w>', 'players</w>', 'i', 's</w>', 'a</w>']
Fast BPE      : ['the</w>', 'city</w>', 'b', 'owl</w>', 'i', 's</w>', 'a</w>', 'part</w>', 'of</w>', 'c']
Fast BPE      : ['the</w>', 'ti', 'west</w>', 'j', 'o', 'i', 'nt</w>', 'venture</w>', 'was</w>', 'a</w>']
Fast BPE      : ['this</w>', 'i', 's</w>', 'a</w>', 'l', 'i', 'st</w>', 'of</w>', 'characters</w>', 'and</w>']
Fast BPE      : ['k', 'b', 'y', 'z</w>', '9', '6</w>', '5</w>', 'fm', '</w>', 'known</w>']
Fast BPE      : ['m', 'ar', 'z', 'b', '</w>', 'n</w>', 'or</w>', 'm', 'ar', 'z']
Fast BPE      : ['the</w>', 'kar', 'o</w>', 'or</w>', 'kar', 'o', 'nese</w>', 'ar', 'e</w>', 'a</w>']
Fast BPE      : ['r', 'e', 'n', 'zo</w>', 'rab', 'elli', 'no</w>', 'b', 'or', 'n</w>']
Fast BPE      : ['i', 'vu', 'ji', 'vi', 'k</w>', 'meaning</w>', 'place</w>', 'where</w>', 'i', 'ce</w>']
Fast BPE      : ['captain</w>', 'frederick</w>', 'john</w>', 'h', 'ol', 'r', 'oyd</w>', 'i', 's</w>', 'a</w>']
Fast BPE      : ['the</w>', 'tr', 'i', 'ni', 'ty</w>', 'c', 'e', 'n', 'tr', 'e</w>']
Fast BPE      : ['the</w>', 'o', 'y', 'ster</w>', 'f', 'e', 'a', 'st</w>', 'i', 's</w>']
Fast BPE      : ['z', 'a', 'h', 'oor</w>', 'u', 'l', '</w>', 'akh', 'l', 'aq</w>']
Fast BPE      : ['b', 'r', 'i', 'an</w>', 'pro', 'th', 'er', 'oe</w>', 'b', 'or']
Fast BPE      : ['b', 'ell', 'eeks</w>', 'i', 's</w>', 'a</w>', 'small</w>', 'village</w>', 'and</w>', 't']
Fast BPE      : ['i', 'van</w>', 'petr', 'o', 'v</w>', 'may</w>', 'r', 'e', 'f', 'er</w>']

In [30]:
import pandas as pd
df = pd.read_csv("../data/Lexique4/Lexique4.tsv", sep="\t",
                 usecols=["1_Mot", "5_Cgram","31_MorphoStruct", "32_MorphoDecomp"])

In [ ]:
df = df.dropna(subset=["1_Mot", "5_Cgram", "31_MorphoStruct", "32_MorphoDecomp"])

df = df[df["5_Cgram"] == "VER"]
df = df[~df["32_MorphoDecomp"].str.contains(r"\[", regex=True)]

benchmark = (df[df["31_MorphoStruct"] != "0-1-0"]
               .groupby("31_MorphoStruct")
               .filter(lambda x: len(x) >= 100)
               .groupby("31_MorphoStruct")
               .apply(lambda x: x.sample(min(len(x), 100), random_state=42))
               .reset_index(level=0)
               .reset_index(drop=True))
benchmark = benchmark[~benchmark["32_MorphoDecomp"].str.contains(r"\[", regex=True)]
benchmark

    31_MorphoStruct       1_Mot 5_Cgram        32_MorphoDecomp
0             0-1-1   négociant     VER         /négoc(e).iant
1             0-1-1       tigré     VER             /tigr(e).é
2             0-1-1       blâme     VER            /blâm(er).e
3             0-1-1   aggloméré     VER         /agglomér(é).é
4             0-1-1    accabler     VER         /accabl(er).er
..              ...         ...     ...                    ...
595           2-1-1  réassigner     VER  _ré_a(d)/s/sign(e).er
596           2-1-1  désemparer     VER     _dés_em/par(er).er
597           2-1-1   réengager     VER       _ré_en/gag(e).er
598           2-1-1  réencadrer     VER      _ré_en/cadr(e).er
599           2-1-1    rempiler     VER        _r_em/pil(e).er

[600 rows x 4 columns]

In [ ]:
import re

def parse_morph(decomp: str) -> list(str):
    clean = decomp.replace("_", "/").replace("{", "").replace("}", "")
    morphemes = re.split(r"[/.]", clean)
    morphemes = [re.sub(r"\(.*?\)", "", m).strip() for m in morphemes]
    return [m for m in morphemes if m]

# 596	2-1-1	réassigner	VER	_ré_a(d)/s/sign(e).er
parse_morph("_ré_a(d)/s/sign(e).er")

['ré', 'a', 's', 'sign', 'er']

In [71]:
from datasets import load_dataset

benchmark = load_dataset("axmeu/FrVMorpho")["train"].to_pandas()

In [72]:
benchmark.sample()

    31_MorphoStruct     1_Mot 5_Cgram     32_MorphoDecomp       morphemes
141           0-1-2  bombardé     VER  /bomb(e).ard(er).é  [bomb, ard, é]